# Generated by Django 3.0 on 2022-02-12 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tall', models.IntegerField(verbose_name='키(cm)')),
                ('weight', models.IntegerField(verbose_name='몸무게(kg)')),
                ('thigh', models.CharField(choices=[['LEFT', '남는다'], ['FIT', '딱맞다'], ['LOOSE', '널널하다']], max_length=10, verbose_name='허벅지')),
                ('foot', models.IntegerField(verbose_name='발 사이즈(mm)')),
                ('underwear', models.IntegerField(verbose_name='속옷 크기')),
                ('body', models.CharField(choices=[['A', '허벅지 평균 이상'], ['B', '종아리 평균 이상'], ['C', '마른체형'], ['D', '골격 체형'], ['E', '골반 발달'], ['F', '딱히 없다']], max_length=10, verbose_name='체형')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='카테고리')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name_plural': '스타일 추천 요청',
            },
        ),
    ]
