# Generated by Django 3.2.7 on 2021-09-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='코드명')),
                ('attached', models.FileField(upload_to='files/', verbose_name='첨부 파일')),
            ],
        ),
    ]
