# Generated by Django 3.2.7 on 2021-10-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='attached',
            field=models.FileField(upload_to='', verbose_name='첨부 파일'),
        ),
    ]
