# Generated by Django 3.2.9 on 2021-12-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0003_auto_20211204_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='attached',
            field=models.FileField(upload_to='fileserver/', verbose_name='첨부 파일'),
        ),
    ]
