# Generated by Django 3.0 on 2022-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name="주소 '/terms/<here>'")),
                ('name', models.TextField(verbose_name='약관 명')),
                ('contents', models.TextField(verbose_name='약관 명')),
            ],
        ),
    ]
