# Generated by Django 3.0 on 2022-02-04 17:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='contents',
            field=ckeditor.fields.RichTextField(verbose_name='약관 내용'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='name',
            field=models.CharField(max_length=100, verbose_name='약관 명'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='url',
            field=models.CharField(max_length=100, verbose_name="주소 '/terms/<here>'"),
        ),
    ]
