# Generated by Django 3.0 on 2022-02-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_auto_20220205_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name': '이용약관', 'verbose_name_plural': '이용약관'},
        ),
    ]
