# Generated by Django 3.0 on 2022-02-05 15:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_auto_20220205_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='약관 내용'),
        ),
    ]
