import '../styles/globals.css'
import 'semantic-ui-css/semantic.min.css'
import Head from 'next/head'
import { MobileContext } from 'src/components/mobile'


function App({ Component, pageProps }) {
  return (
    <>
        <Head>
          <title>Copyc</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/copyc.ico" />
        </Head>
        <MobileContext>
          <Component {...pageProps} />
        </MobileContext>
    </>
  )
}

export default App
