# Generated by Django 3.0 on 2022-02-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_event',
            field=models.BooleanField(default=False, verbose_name='플러스친구 추가 후 이벤트 소식받기'),
        ),
        migrations.AddField(
            model_name='user',
            name='agree_marketing',
            field=models.BooleanField(default=False, verbose_name='마케팅 활용'),
        ),
    ]
