# Generated by Django 3.0 on 2023-05-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agree_event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='agree_marketing',
        ),
        migrations.AddField(
            model_name='user',
            name='coin',
            field=models.IntegerField(default=1000, verbose_name='코인'),
        ),
    ]
