# Generated by Django 3.0 on 2022-02-05 22:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='카테고리 명')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='질의 제목')),
                ('contents', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='질의 내용')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='답변 내용')),
                ('is_answered', models.BooleanField(default=False, verbose_name='답변 여부')),
                ('question_at', models.DateTimeField(auto_now_add=True, verbose_name='질의 등록일')),
                ('answered_at', models.DateTimeField(default=None, null=True, verbose_name='답변 등록일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.Category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name_plural': '질의답변',
            },
        ),
    ]
