# Generated by Django 3.0 on 2022-02-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '문의유형 관리'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.Category', verbose_name='문의유형'),
        ),
    ]
