# Generated by Django 3.0 on 2022-02-08 15:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0002_auto_20220206_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='질의자'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='답변 내용'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_answered',
            field=models.BooleanField(blank=True, default=False, verbose_name='답변 여부'),
        ),
    ]
