# Generated by Django 3.0 on 2022-02-05 15:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='상품내용'),
        ),
    ]
