# Generated by Django 3.0 on 2022-02-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220206_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10, verbose_name='크기')),
                ('tall_row', models.IntegerField(verbose_name='키(최소)')),
                ('tall_high', models.IntegerField(verbose_name='키(최대)')),
                ('weight_row', models.IntegerField(verbose_name='몸무게(최소)')),
                ('weight_high', models.IntegerField(verbose_name='몸무게(최대)')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product', verbose_name='상품')),
            ],
            options={
                'verbose_name_plural': '사이즈',
            },
        ),
    ]
