# Generated by Django 3.0 on 2023-05-19 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='attached',
            field=models.FileField(default='', upload_to='fileserver/', verbose_name='첨부 파일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='코드명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
