# Generated by Django 3.0 on 2023-05-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_productimage_attached'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
